### ISSUE TITLE
ブログ記事の Markdown を site-data へ移行する

### ISSUE THREAD

**Issue by shun-shobon** [approvers/approvers.github.io#102]
現在のリポジトリの状態ではブログの記事とソースコードが共存することになってしまっているのでこの状況を変えたいと考えています。
ブログのマークダウンを管理するリポジトリを新しく立てて、GitHub Actionsを用いて記事を取得、ビルドしてデプロイというようなワークフローを組むべきだと思います。

**Comment by MikuroXina** [comment]
リポジトリ内のファイルを取得するだけなら, GitHub Actions 時に受け取ったトークンを使って, TypeScript コードから API 経由で取得する感じになりそうです

**Comment by siketyan** [comment]
GitHub Actions で渡されるトークンはそのリポジトリ以外のプライベートリポジトリで使えないので気をつけてください（この Org でプライベートにすることはなさそうですが）

**Comment by MikuroXina** [comment]
ん, あぁ `GITHUB_TOKEN` のことではなく `secrets` にセットされているのを読み取るということです.

**Comment by MikuroXina** [comment]
960c8dd の作業により, フォルダをダウンロードする形で解決しているので Close します.
