### ISSUE TITLE
参加方法のページ修正案

### ISSUE THREAD

**Issue by MikuroXina** [approvers/approvers.github.io#11]
公式サイトの参加方法のページを、

```
お前ごときが入れると思うなカス
```

みたいに辛辣な感じにしてみたいです

**Comment by laminne** [comment]
`お前ごときが入れると思うなカス`　を、
`お前ごときが入れると思うなカス(真顔`　にしたほうがもっと辛辣なかんじになるとおもいます

**Comment by MikuroXina** [comment]
しょーもない上に放置されているので Close
