### ISSUE TITLE
[important]main ブランチの保護ルールの見直し

### ISSUE THREAD

**Issue by MikuroXina** [approvers/approvers.github.io#138]
main ブランチへの PR は現在 2 人以上の Approve でマージ可能になりますが, あまりにもレビューが遅く非効率的になっているため見直しを提案します. なお, Code Owner は継続しても問題ないと思います.

main ブランチの保護ルールを, 1 人以上の Approve でマージ可能に変更してはどうでしょうか? Approve 人数ルールの撤廃も含めて検討したいです.

**Comment by mirror-kt** [comment]
mainに直pushさえしなければどうにかなるだろ主義でいきたいです

**Comment by MikuroXina** [comment]
見直しの方針を #188 で新しく書き直したので Close します.
