### ISSUE TITLE
ブランチの名前変更

### ISSUE THREAD

**Issue by mirror-kt** [approvers/approvers.github.io#142]
# 概要
現在の`master`ブランチはビルド済みの成果物をデプロイするブランチとなっており、https://approvers.dev にて公開されています。
実際のソースコードは`dev`ブランチにあるのですが、これは誤解を生む元になるため、ブランチのリネームを提案します。

|旧ブランチ名|新ブランチ名|
|---|---|
|master|gh-pages|
|dev|master(もしくはmain)|

# 行うべき作業
ブランチ名を変更すると以下の作業が必要になります。
* GitHub Pagesのデプロイブランチの変更
* GitHub Actionsのデプロイ先ブランチの変更

**Comment by mirror-kt** [comment]
たいした変更でもないので1週間の猶予をおき明確な反対が得られなければ私が勝手に執行します。

**Comment by MikuroXina** [comment]
個人的には, 混乱を防ぐためにも `dev` からは `main` へ変更したいです

**Comment by mirror-kt** [comment]
> 個人的には, 混乱を防ぐためにも `dev` からは `main` へ変更したいです

これ単体で行うと`main`と`master`が存在することになって余計ややこしいのでついでに`master`から`gh-pages`にも変えたいですね…

**Comment by mirror-kt** [comment]
`gh-pages`はなんかGitHub Pagesに依存してる感じがしていやと言われたので`release`にします。
