### ISSUE TITLE
ロールに色を

### ISSUE THREAD

**Issue by MikuroXina** [approvers/approvers.github.io#15]
(自分用メモ)
メンバー紹介ページのロール部分ですが、
Discord 鯖内でのロールの色をテキストの背景にしてみたいです
私がそのうちやります

**Comment by unios103** [comment]
あまり賛成できないです（↓理由）
- テキストの背景に色を入れることで**文字よりもロールの方が**目立ってしまう
- サイトの訪問者にとっては、誰にどんなロールがついているかということはあまり**重要ではない**
- 色が多くなるほど**扱いが難しくなる**
- そもそも **ロールの色（彩度、明度等）** があっていない
  - 上二つにより、サイトの**デザインが崩れやすくなる**し、**統一感がなくなる**

**Comment by MikuroXina** [comment]
私は楽しい感じになるかなと思って提案したのですが...
どんな見た目になるのか試してみたので、画像を置いておきます。

<img width="1254" alt="スクリーンショット 2020-05-20 19 56 48" src="https://user-images.githubusercontent.com/10331164/82438680-6535f280-9ad4-11ea-8860-78dcf852b827.png">
<img width="320" alt="スクリーンショット 2020-05-20 19 57 09" src="https://user-images.githubusercontent.com/10331164/82438689-69621000-9ad4-11ea-9437-8a892c7b4a02.png">

**Comment by MikuroXina** [comment]
まあまあ反対意見が多かったので没案になりました。
