### ISSUE TITLE
Q,A（ホーム）のデザインを修正する

### ISSUE THREAD

**Issue by unios103** [approvers/approvers.github.io#34]
文章の一部をサブタイトル扱いするのは変なので、そう見えないようにするかQ,Aではない何かに変更する

**Comment by mirror-kt** [comment]
(横槍失礼)おそらく[こういうこと](http://kokoro.kir.jp/word/dropcap.html)だと思ふ

**Comment by MikuroXina** [comment]
CSS だと `:first-letter` を使えば実現できそうです。

**Comment by unios103** [comment]
[Pull requests](https://github.com/approvers/approvers.github.io/pull/33#discussion_r427859905)
流石に２つ目の例だとおかしいので、デザイン変えた方がいいなと

**Comment by unios103** [comment]
@MikuroXina 対応状況的に厳しいと思います

**Comment by MikuroXina** [comment]
ドロップキャップを実現するなら、`:first-letter` に対して `float: left` で左に割り込ませるしかなさそうです。
