### ISSUE TITLE
(お気持ち表明）Q.Aのずれ

### ISSUE THREAD

**Issue by kawaemon** [approvers/approvers.github.io#36]
お気持ち表明なので気が向いたら直していただければ、、、
Noto Sans JPだと字幅のせいで少しずれるようです。

<img width="317" alt="Screen Shot 2020-05-20 at 20 54 15" src="https://user-images.githubusercontent.com/34652535/82443391-60753c80-9adc-11ea-906d-2403ac61d4a7.png">

**Comment by Siketyan** [comment]
```css
font-family: monospace;
```

にするってマジ？
