### ISSUE TITLE
master ブランチにブランチ保護が設定されていない

### ISSUE THREAD

**Issue by Siketyan** [approvers/approvers.github.io#37]
デプロイされるのは master ブランチっぽいのでここに直接マージ or push できてしまうのでは…？

**Comment by shun-shobon** [comment]
`master`ブランチにブランチ保護を設定しました。ご報告ありがとうございます。
![スクリーンショット 2020-05-20 22 16 48](https://user-images.githubusercontent.com/37236438/82450424-a7b4fa80-9ae7-11ea-9594-0be6fdef6f0f.png)
