### ISSUE TITLE
members-dbへ対応

### ISSUE THREAD

**Issue by kawaemon** [approvers/approvers.github.io#62]
members-dbから引っ張ってきて描画するようにすると良さそう

### 問題点
- members-dbにはroleがない -> いい感じにmapしてあげる必要がある

**Comment by MikuroXina** [comment]
もう一つの問題点として、members-db は ID を返すのでそれを実際のユーザページへの URL に変換する処理が必要なのですが、
そのままだと例えば GitHub API の場合一定時間内のアクセス制限数 (未認可の場合) をメンバー人数的に超えてしまうので、

- 認可トークンを付与してビルドを実行する
- members-db 側がユーザページへの URL も返す

などの対策を講じる必要があります

**Comment by Siketyan** [comment]
個人的には members-db(?:-rust)? の役割を最低限に抑えたくて， Discord や GitHub の ID と URL (とか Screen Name とか) とをリンクしてキャッシュするアプリケーションをもう一つ挟むべきかなと思っています

**Comment by MikuroXina** [comment]
上記の問題は siketyan の協力により解決済みです.

現在は「members-db に role がない」という問題により作業が滞っています.

**Comment by siketyan** [comment]
role は members-db-gateway から取得した Discord ID をもとに Discord API から取得すればいいんでねと思っていますがヒエラルキーをどうするかが問題ですね

**Comment by MikuroXina** [comment]
表示されるロールのフィルタを作って, 取得したロールのうち該当するものの中で最も優位なロールを表示すればいいですかね

**Comment by siketyan** [comment]
Discord はロールにヒエラルキーを持っているっぽいので，これの一番上を使えばよさそう（例の大臣については全知全能の神ロールのほうが上なので問題なさそう）

**Comment by siketyan** [comment]
メンバー紹介に表示しているロールがサーバのロール全体で一番上である，またはそれでも問題ないのであれば特にフィルタする必要はないと感じました（設定めんどいし）

**Comment by MikuroXina** [comment]
問題なのは `参政権` だったりします

**Comment by siketyan** [comment]
参政権ってそんなに強かったっけ？

**Comment by MikuroXina** [comment]
`超スーパーガチプロ` よりは上です

**Comment by siketyan** [comment]
ヒィ
参政権を下にすることはできないんかな
できないなら allowlist / blocklist のどっちかを組まないといけないか、、

**Comment by MikuroXina** [comment]
現在それを組む作業中です

**Comment by MikuroXina** [comment]
組み終わりましたが, CI で証明書の検証エラーが発生するために作業が滞っています

**Comment by MikuroXina** [comment]
証明書の問題は解決しました, 細かいバグ修正中です

**Comment by MikuroXina** [comment]
contacts-gateway へ一度に大量のリクエストを送るのですが, その際に 504 Gateway Timeout が返される現象が起こるため停滞中です

**Comment by MikuroXina** [comment]
また, members-db にあるいくつかの twitter の ID を contacts-gateway に渡すと 404 Not Found が返る現象も確認しています

**Comment by MikuroXina** [comment]
上記の問題の原因が特定できました. メンバーのデータベースから取得した YAML (かつては JSON) データをパースする際に, 当該 ID 部分が数値になっているため倍精度浮動小数点数としてパースされます. その結果, 下二桁が切り落とされて `00` になってしまい, 正常に値が読み取れないことでバグが発生していました.
現在修正作業中です.

**Comment by MikuroXina** [comment]
site-data に今まで通りの `list.yaml` を配置してそれを読む方向で実装することにしています. それにあたって site-data 側のデータ更新の実装が必要です.
