### ISSUE TITLE
†限界リンク集†

### ISSUE THREAD

**Issue by Colk-tech** [approvers/approvers.github.io#66]
色々アカウントが増えてきたのでリンク集ちょっと欲しいかも

 - GitHub
    - [approvers](https://github.com/approvers)
 - Twitter
    -  [@UFIApprovers](https://twitter.com/UFIApprovers)
 - YouTube
    -  [UCUtr3DOhkcuunsHrAJyWylA](https://www.youtube.com/channel/UCUtr3DOhkcuunsHrAJyWylA)
 - connpass
    - [approvers](https://approvers.connpass.com)
 - Qiita
    - [approvers](https://qiita.com/organizations/approvers)
- BinTray
   - [Approvers](https://bintray.com/approvers)
- NPM
	- [Approvers](https://www.npmjs.com/settings/approvers/packages)
- HackMD
	- [@approvers](https://hackmd.io/@approvers)

**Comment by loxygenK** [comment]
- BinTree
   - [Approvers](https://bintray.com/approvers)

**Comment by potyama** [comment]
↑のこるくが張ったTwitterのリンク間違ってる?凍結されているので、こっちで。
 - Twitter
    -  [@UFIApprovers](https://twitter.com/UFIApprovers)

**Comment by shun-shobon** [comment]
- NPM
	- [Approvers](https://www.npmjs.com/settings/approvers/packages)

**Comment by Colk-tech** [comment]
> ↑のこるくが張ったTwitterのリンク間違ってる?凍結されているので、こっちで。
> 
> * Twitter
>   
>   * [@UFIApprovers](https://twitter.com/UFIApprovers)

ア！ありがとうございます！

**Comment by unios103** [comment]
限界リンク集って新たにページを生やすべき？

**Comment by mirror-kt** [comment]
hackmdにapproversのteamを生やしました
https://hackmd.io/@approvers/

**Comment by loxygenK** [comment]
> * BinTree
>   
>   * [Approvers](https://bintray.com/approvers)

BinTrayでした本当にごめんなさいゆるして

**Comment by MikuroXina** [comment]
#140 にて対応済みです.
