### ISSUE TITLE
ヘッダーのデザインの改善

### ISSUE THREAD

**Issue by shun-shobon** [approvers/approvers.github.io#97]
ヘッダーの文字が多すぎてスマホサイズではレイアウトが崩れます

![デザイン崩れ](https://user-images.githubusercontent.com/37236438/96243001-1a66cb00-0fdf-11eb-82b0-8b8feaeb3063.png)

**Comment by MikuroXina** [comment]
#99 でまたテキストが減るのでこの現象は見られなくなりますが, 根本的な解決ではありません. #99 がマージされても Close しないでください.

サイドメニューにするなどの工夫で対策することになりそうです.
